### ISSUE TITLE
No Assests Floder

### ISSUE THREAD

**Issue by ahmedTareque** [michaelroudnitski/Tabs#13]
Would you please share the assets folder containing graphics?

**Comment by michaelroudnitski** [comment]
You can find the images I used and more at [undraw.co](https://undraw.co)

Hope that helps!

**Comment by trytelework** [comment]
Hey Michael. Great package! I was going to open this same issue - only because the project won't build without the assets. It freezes on the login page because it is depending on unavailable fonts and graphics:

![Screenshot_1580165687](https://user-images.githubusercontent.com/59515642/73221140-c270f700-4125-11ea-9e03-f99926c2a343.png)
